#!/bin/bash
# Apply section-level preferences updates to _relationships_section_v2.html

echo "This script documents the changes needed for _relationships_section_v2.html"
echo "The changes mirror those made to _relationships_section_configurable.html"
echo ""
echo "CHANGES NEEDED:"
echo "==============="
echo ""
echo "1. UPDATE saveFilterPreference function (line ~801):"
echo "   - Change API endpoint from '/api/relationship_filter_preferences' to '/api/section_relationship_preferences'"
echo "   - Add entryTypeId and sectionId to payload"
echo "   - Update payload keys: section_id -> section_id, specific_state -> filter_specific_states"
echo ""
echo "2. UPDATE loadFilterPreferences function (line ~844):"
echo "   - Change API endpoint to '/api/section_relationship_preferences?entry_type_id=\${entryTypeId}&section_id=\${sectionId}'"
echo "   - Update response key: specific_state -> filter_specific_states"
echo ""
echo "3. FIND AND UPDATE hideCard/unhideCard functions (if they exist):"
echo "   - Replace localStorage with API calls to /api/section_relationship_preferences"
echo "   - Add is_hidden: true/false to payload"
echo ""
echo "4. UPDATE applyHiddenCardsOnLoad function:"
echo "   - Replace localStorage with API call to load section preferences"
echo "   - Filter for is_hidden === true"
echo ""
echo "The v2 template should match the configurable template's approach exactly."
